[package]
name = "streaming_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures-util = "0.3.31"
ratatui = "0.29.0"
crossterm = "0.29.0"
async-openai = "0.28.1"
dotenv = "0.15.0"
anyhow = "1.0.98"
